; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B2FBB8E9-C1E1-4B08-A360-4D159B411DD2}
AppName=Pharma Soft
AppVersion=Pharma Soft 1.0
;AppVerName=Pharma Soft Pharma Soft 1.0
AppPublisher=Pharma Soft, Inc.
DefaultDirName={pf}\Pharma Soft
DefaultGroupName=Pharma Soft
AllowNoIcons=yes
OutputDir=C:\xampp-portable\htdocs\pruevas\autocompletado
OutputBaseFilename=Pharma Soft setup
SetupIconFile=C:\Users\Djs\Pictures\im\illust_studio.ico
Password=123456
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\xampp-portable\htdocs\pruevas\index.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\css\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\xampp-portable\htdocs\pruevas\fonts\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\xampp-portable\htdocs\pruevas\img\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\xampp-portable\htdocs\pruevas\js\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\xampp-portable\htdocs\pruevas\php\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\xampp-portable\htdocs\pruevas\entrada.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\index.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina2.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina3.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina4.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina5.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina6.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina7.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina8.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\pagina9.php"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Pharma Soft"; Filename: "{app}\index.php"
Name: "{group}\{cm:UninstallProgram,Pharma Soft}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Pharma Soft"; Filename: "{app}\index.php"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Pharma Soft"; Filename: "{app}\index.php"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\index.php"; Description: "{cm:LaunchProgram,Pharma Soft}"; Flags: shellexec postinstall skipifsilent

