; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{48821360-7B99-4853-A65E-1115941E3AD2}
AppName=Pharma Soft
AppVersion=Pharma Soft 1.0
;AppVerName=Pharma Soft Pharma Soft 1.0
AppPublisher=Pharma Soft, Inc.
DefaultDirName={pf}\Pharma Soft
DefaultGroupName=Pharma Soft
AllowNoIcons=yes
OutputDir=C:\Users\Djs\Desktop
OutputBaseFilename=Pharma Soft setup
SetupIconFile=C:\Users\Djs\Pictures\im\illust_studio.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\xampp-portable\htdocs\pruevas\index.php"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\xampp-portable\htdocs\pruevas\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Pharma Soft"; Filename: "{app}\index.php"
Name: "{group}\{cm:UninstallProgram,Pharma Soft}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\Pharma Soft"; Filename: "{app}\index.php"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Pharma Soft"; Filename: "{app}\index.php"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\index.php"; Description: "{cm:LaunchProgram,Pharma Soft}"; Flags: shellexec postinstall skipifsilent

